### ISSUE TITLE
smiler-mercer fn misisng

### ISSUE THREAD

**Issue by behrica** [generateme/fastmath-clustering#1]
This libraty + fastmath 3.0beta misses the below fn:

```
(defn smile-mercer
  "Create Smile Mercer Kernel object

  Used to pass to Smile constructors/functions."
  [k]
  (reify
    MercerKernel (k [_ x y] (k x y))
    IFn (invoke ^double [_ x y] (k x y))))

`

**Comment by genmeblog** [comment]
There are no kernels for clustering so it's not needed here.

Fastmath 3.0 doesn't depend on SMILE at all, so it's not possible to have it there.

I think this should exists in scicloj.ml related liberaries.

**Comment by behrica** [comment]
Just wanted to mention it.
I recentely ported scicloj.ml.smile to use fastmath 3.0,
and that function was missing.
So I added it in  scicloj.ml.smile.

All tests pass, so it seems to be fine.

**Comment by behrica** [comment]
It just seems to say that 
fastmath 3.0 +  fastmath-clustering

is not "backwards compatible" 

with  fastmath 2.4

which I though was a maybe a "goal" .

**Comment by genmeblog** [comment]
I tried to cover as much as possible. But it couldn't be fully backward compatible since some functionality dissapeared with SMILE (like some interpolations, kernels, distributions). 

Anyway, I think `scicloj.ml.smile` is a good place for this function.
